# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Portfolio Code</title>
  <link rel="stylesheet" type="text/css" href="css.css">
  <link rel="stylesheet" href="style.css" />
  <script src="https://kit.fontawesome.com/66aa7c98b3.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
</head>

<body>
  <header class="header">
    <nav class="navbar">
      <div class="navbar-container container">
        <div>
          <h1 class="navbar-brand"> Hamsini </h1>
        </div>
        <ul class="menu-items">
          <li><a href="#about">About</a></li>
          <li><a href="#my-works">Portfolio</a></li>
          <li><a href="#contact-me">Contact</a></li>
        </ul>
      </div>
    </nav>
    <div class="home-content" id="home-page">
      <div class="name">
        <h1>Hi, I'm Hamsini</h1>
        <p>Associate Software Engineer</p>
      </div>
      <div class="angle-down-icon">
        <a href="#about"><i class="fas fa-angle-down"></i></a>
      </div>
    </div>
  </header>
  <section class="about-me" id="about">
    <div class="container">
      <div class="about-content">
        <div class="left-content">
          <div>
            <h1 class="about-heading">About Me</h1>
          </div>
         
          <p>
            I am a highly motivated and enthusiastic professional with a strong passion for AWS DevOps. With a background in computer science and engineering, I am eager to embark on a career in the field of cloud computing and DevOps, leveraging my technical skills and knowledge to contribute to innovative solutions and continuous improvement in software development and deployment processes.
          </p>
          <div class="work-arrow">
            <p>
              <a href="#my-works">Check out my work <i class="fas fa-arrow-down"></i></a>
            </p>
          </div>
        </div>
        <div class="skills">
          <div class="right-content">
            <div>
              <h1 class="skills-heading">My Skills</h1>
            </div>
            <div class="skills-bar">
              <div class="bar">
                <div class="info">
                  <span>Linux/Unix</span>
                </div>
                <div class="progress-line"><span class="Linux/Unix" style="width: 97%;"></span></div>
                <div class="bar">
                  <div class="info">
                    <span>AWS Management Console</span>
                  </div>
                  <div class="progress-line"><span class="AWS Management Console" style="width: 95%;" ></span></div>
                  <div class="bar">
                    <div class="info">
                      <span>Git</span>
                    </div>
                    <div class="progress-line"><span class="Git" style="width: 97%;"></span></div>
                    <div class="bar">
                      <div class="info">
                        <span>Kubernetes</span>
                      </div>
                      <div class="progress-line"><span class="Kubernetes"></span></div>
                      <div class="bar">
                        <div class="info">
                          <span>Terraform</span>
                        </div>
                        <div class="progress-line"><span class="Terraform"></span></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="work-arrow-2">
              <p>
                <a href="#my-works">Check out my work <i class="fas fa-arrow-down"></i></a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="my-works">
    <div class="portfolio">
      <div class="proj-heading">
        <h1>Portfolio</h1>
      </div>
      <div class="portfolio-content container">
        <div class="proj-1">
        
          <div class="proj1-details">
            <i class="fab fa-html5"></i>
            <i class="fab fa-css3-alt"></i>
            <i class="fab fa-js"></i>
            <h2> Setup a LAMP Server on Ubuntu for PHP Web Development</h2>
            <p>This Bash script installs the Lamp stack which is a combination of operating system and open-source software stack. This LAMP setup includes the installation of Apache HTTP Server, MySQL and PHP on the top of Ubuntu.</p>
            <button><a href="https://github.com/dev-ops-aws/sonix_batch3/tree/pavan/linux/linux-proj/project-1" target="blank">View source <i
                  class="fas fa-external-link-alt"></i></a>
            </button>
           
          </div>
        </div>

        <div class="proj-2">
          
  <div class="proj2-details">
    <i class="fab fa-html5"></i>
    <i class="fab fa-css3-alt"></i>
    
           
             <i
                  class="fas fa-external-link-alt"></i></a>
            </button>
             <i
                  class="fas fa-external-link-alt"></i></a>
            </button>
          </div>

        </div>
        
          
        </div>
      </div>
    </div>
  </section>
  <div class="contact" id="contact-me">
    <div class="container">
      <div class="contact-content">
        <h2>Contact Me</h2>
        <p class="mail">
          Get in touch with me <i class="fas fa-arrow-right"></i> hamsini@sonixhub.com @gmail.com
        </p>
        <p class="links">Or find me on:</p>
        <a href="https://www.linkedin.com/in/hamsini-d-b7544414a" target="blank"><i class="fab fa-linkedin">
            Linkedin</i></a>
     
        <a href="https://github.com/hams77" target="blank"><i class="fab fa-github"></i> Github</a>
        <a href="https://hashnode.com/" target="blank"><i class="fab fa-dev"></i> Hashnode </a>
       
       
      </div>
    </div>
  </div>
 
</body>

</html>




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
